base: &base
 database_prefix: couchdb_model_skeleton

development:
  host: localhost
  port: 5984
  <<: *base
  
test:
  host: localhost
  port: 5984
  <<: *base

test:
  host: localhost
  port: 5984
  <<: *base
